"""Add project settings and soft delete fields

Revision ID: 184cc017dcaf
Revises: 379eb5627c24
Create Date: 2025-09-13 06:32:11.689432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184cc017dcaf'
down_revision: Union[str, None] = '379eb5627c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'settings')
    # ### end Alembic commands ###
