"""Add AI model configuration table

Revision ID: 379eb5627c24
Revises: fdc3fbd4fa54
Create Date: 2025-09-13 05:47:15.558175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379eb5627c24'
down_revision: Union[str, None] = 'fdc3fbd4fa54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
