"""add_task_dependencies_and_subtasks

Revision ID: 7034f672986e
Revises: 184cc017dcaf
Create Date: 2025-09-13 08:52:16.974712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7034f672986e'
down_revision: Union[str, None] = '184cc017dcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_id', name='unique_task_dependency')
    )
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('test_strategy', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('order_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'])
    op.drop_column('tasks', 'dependencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dependencies', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'order_index')
    op.drop_column('tasks', 'test_strategy')
    op.drop_column('tasks', 'parent_id')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
